INSERT INTO CATEGORIA (id, categoria) VALUES ('1', 'ALIMENTACAO');
INSERT INTO CATEGORIA (id, categoria) VALUES ('2', 'SAUDE');
INSERT INTO CATEGORIA (id, categoria) VALUES ('3', 'LAZER');
INSERT INTO CATEGORIA (id, categoria) VALUES ('4', 'MORADIA');
INSERT INTO CATEGORIA (id, categoria) VALUES ('5', 'EDUCACAO');
INSERT INTO CATEGORIA (id, categoria) VALUES ('6', 'OUTROS');

