INSERT INTO CATEGORIA (id, descricao) VALUES ('1', 'ALIMENTACAO');
INSERT INTO CATEGORIA (id, descricao) VALUES ('2', 'SAUDE');
INSERT INTO CATEGORIA (id, descricao) VALUES ('3', 'LAZER');
INSERT INTO CATEGORIA (id, descricao) VALUES ('4', 'MORADIA');
INSERT INTO CATEGORIA (id, descricao) VALUES ('5', 'EDUCACAO');
INSERT INTO CATEGORIA (id, descricao) VALUES ('6', 'OUTROS');

